name: Update Code

on:
  push:
    branches:
      - main
      
  schedule:
    - cron: "0 13 * * *" # 매일 오후 10시에 수행

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Check if there are any changes
        id: verify_diff
        run: |
          git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit and push
        if: steps.verify_diff.outputs.changed =='true'
        run: |
          git config --global user.name '5a6io'
          git config --global user.email '${{ secrets.EMAIL }}'
          git status
          git add .
          git commit -m "Update Code"
          git push -u origin main